name: Trivy DB
on: push
        #:  schedule:
        #:    - cron:  '0 */12 * * *'

jobs:
  build:
    name: Build DB
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Install bbolt
      run: go get -v github.com/etcd-io/bbolt/cmd/bbolt

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Download vuln-list and advisories
      run: make db-fetch

    - name: Build the binary
      run: make build

    #
    # Full DB
    #
    - name: Build full database
      run: make db-build

    - name: Compact DB
      run: make db-compact

    #
    # Light DB
    #
    - name: Build light database
      run: make db-build
      env:
        DB_TYPE: trivy-light

    - name: Compact DB
      run: make db-compact
      env:
        DB_TYPE: trivy-light

    #
    # Push Docker image
    #
    - name: Build DB as Docker image
      run: |
        docker build -f - -t knqyf263/trivy-db:latest . <<EOF
        FROM busybox
        COPY assets/trivy.db .
        EOF

    - uses: azure/docker-login@v1
        with:
          username: 'knqyf263'
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push
      run: docker push knqyf263/trivy-db:latest

    #
    # Upload
    #
    #    - name: Compress assets
    #      run: make db-compress
    #
    #    - name: Upload assets
    #      run: ./trivy-db upload --dir assets
    #      env:
    #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #
